### ISSUE TITLE
doc: Modify the correct project path.

### ISSUE THREAD

**Issue by zedy-wj** [Azure-Samples/gpt-video-analysis-in-a-box#2]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> https://github.com/Azure-Samples/gpt-video-analysis-in-a-box?tab=readme-ov-file#deploy-to-azure.

The path `cd gen-ai/a-services/gpt-video-analysis-in-a-box` cannot be found, I guess it should be: `cd ai-services/gpt-video-analysis-in-a-box`. Please synchronize to the latest path or directly `git clone https://github.com/Azure-Samples/gpt-video-analysis-in-a-box.git` then `azd auth login; azd up`.

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

@codebytes for notification.

**Comment by jehayesms** [comment]
@zedy-wj The instructions in the README have been fixed

**Comment by codebytes** [comment]
Thank you!
